config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root 'pages#home'

  get 'about' => 'pages#about'

  get 'careers' => 'pages#careers'

  get 'privacy' => 'pages#privacy'

  get 'terms' => 'pages#terms'

  get 'knowledge' => 'pages#knowledge'
  
  get 'products' => 'pages#products'
  
  get 'blog' => 'pages#blog'
  
  get 'why_flipbank' => 'pages#why_flipbank'
  
  get 'programs' => 'pages#programs'
  
  get 'how_it_works' => 'pages#how_it_works'
  
  get 'partners' => 'pages#partners'
  
  resources :contacts
  get 'contact-us', to: 'contacts#new'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
    validates :name, presence: true
    validates :email, presence: true
    validates :comments, presence: true
end    

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def new
        @contact = Contact.new
    end
    
    def create
        @contact = Contact.new(contact_params)
        if @contact.save
            name = params[:contact][:name]
            email = params[:contact][:email]
            body = params[:contact][:comments]
            ContactMailer.contact_email(name, email, body).deliver
            flash[:success] = "Message sent."
            redirect_to new_contact_path
        else
            flash[:danger] = @contact.errors.full_messages.join(", ")
            redirect_to new_contact_path
        end
    end    

private
    def contact_params
        params.require(:contact).permit(:name, :email, :comments)
    end    
end    

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def careers
  end

  def privacy
  end

  def terms
  end

  def knowledge
  end

  def products
  end
  
  def blog
  end  
  
  def why_flipbank
  end
  
  def programs
  end
  
  def how_it_works
  end
  
  def partners
  end  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<div class="container">
    <div class="row">
        <h3 class="text-center">Contact Us</h3>
        <div class="col-md-4 col-md-offset-4">
            <%= flash[:error] %>
            <div class="well">
                <%= form_for @contact do |f| %>
                    <div class="form-group">
                        <%= f.label :name %>
                        <%= f.text_field :name, class: 'form-control' %>
                    </div>
                    <div class="form-group">
                        <%= f.label :email %>
                        <%= f.text_field :email, class: 'form-control' %>
                    </div>
                    <div class="form-group">
                        <%= f.label :comments %>
                        <%= f.text_area :comments, class: 'form-control'%>
                    </div>
                        <%= f.submit 'Submit', class: 'btn btn-default' %>
                <% end %>
            </div>    
        </div>
    </div>
</div>

app/views/layouts/_header1.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "/", class: "navbar-brand" do %>
          <%= image_tag("FLIPBANK_1.png", size: "202x45") %>
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
          <li class="navtext"><%= link_to 'Why FlipBank?'.html_safe, why_flipbank_path %></li>
          <li class="navtext"><%= link_to 'Programs'.html_safe, programs_path %></li>
          <li class="navtext"><%= link_to 'How It Works'.html_safe, how_it_works_path %></li>
          <li class="navtext"><%= link_to 'Partners'.html_safe, partners_path %></li>
          <li class="navtext"><%= link_to 'Contact Us'.html_safe, contact_us_path %></li>
          <li><%= link_to '<button type="button" class="btn btn-primary">Create Account</button>'.html_safe, about_path %></li>
          <li><%= link_to '<button type="button" class="btn btn-success">Login</button>'.html_safe, about_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flipbank | Lending Made Easy</title>
    <%= csrf_meta_tags %>
    <link href="//fonts.googleapis.com/css?family=Open+Sans:400,700,800" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header1' %>
    <div class="container">
      <% flash.each do |type, msg| %>
        <%= content_tag :div, msg, class: "alert alert-#{type}" %>
      <% end %>
    </div>
      <%= yield %>
    
  </body>
</html>

app/views/pages/about.html.erb
<div class="text-center">
    <h1>About page</h1>
</div>

app/views/pages/blog.html.erb
<div class="text-center">
    <h1>Blog page</h1>
</div>

app/views/pages/careers.html.erb
<div class="text-center">
    <h1>Careers page</h1>
</div>

app/views/pages/home.html.erb
<div class="text-center">
    <h1>Welcome to the Flipbank Home page!</h1>
</div>

app/views/pages/how_it_works.html.erb
<div class="text-center">
    <h1>Find out how Flipbank works</h1>
</div>    

app/views/pages/knowledge.html.erb
<div class="text-center">
    <h1>Knowledge Center page</h1>
</div>

app/views/pages/partners.html.erb
<div class="text-center">
    <h1>Partner with us</h1>
</div>    

app/views/pages/privacy.html.erb
<div class="text-center">
    <h1>Privacy Policy page</h1>
</div>

app/views/pages/products.html.erb
<div class="text-center">
    <h1>Products page</h1>
</div>

app/views/pages/programs.html.erb
<div class="text-center">
    <h1>Our Programs</h1>
</div>

app/views/pages/terms.html.erb
<div class="text-center">
    <h1>Terms & Conditions page</h1>
<div class="text-center">    

app/views/pages/why_flipbank.html.erb
<div class="text-center">
    <h1>Why Use FlipBank</h1>
</div>